#!/bin/bash
instfiles="fuseisomenu.desktop fuseisomenu.sh"
KDE4SRVDIR="${HOME}/.kde/share/kde4/services"
MENUDIR="${KDE4SRVDIR}/ServiceMenus"

if [ -d $KDE4MENUDIR ]; then
    mkdir -p ${MENUDIR} 2>/dev/null
    echo -n "Installing menu to $MENUDIR ... "
    cp -a $instfiles ${MENUDIR}
    [ $? -eq 0 ] && echo "OK" || echo "FAILED"
fi
echo
